@startuml
left to right direction

actor "Player 1" as g1

package "1 Player Game"{
  usecase "Action" as UC1
  usecase "basketball" as bb
  usecase "football" as fb
  usecase "bowling" as bw
  usecase "volleyball" as vb
  usecase "Out of arena" as z
  usecase "Shoot" as sh
  usecase "Shield" as shield
  usecase "Reload" as r
  usecase "Exit Game" as exit
  usecase "update game state" as score
  usecase "Rebirth" as rb
}

g1 --> UC1
g1 --> rb
g1 --> sh

UC1 --> bb: <<include>>
UC1 --> fb: <<include>>
UC1 --> bw: <<include>>
UC1 --> vb: <<include>>
UC1 --> shield: <<include>>
UC1 --> r: <<include>>

g1 --> exit
z --> exit: <<includes>>

bb --> score: <<include>>
fb --> score: <<include>>
bw --> score: <<include>>
vb --> score: <<include>>
r --> score: <<include>>
shield --> score: <<include>>

@enduml